site_name: LDYOM Docs
site_url: https://getechg.github.io/LDYOM_DOC/

nav:
  - Русский:
    - О моде: ru/index.md
    - Первые шаги: ru/getting_started.md
  - English:
    - About: en/index.md
    - Getting started: en/getting_started.md

theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
  font:
    text: Fira Sans
    code: Fira Code
  language: en

plugins:
  - search:
      lang: 
        - en
        - ru

extra:
  alternate:
    - name: English
      link: en
      lang: en
    - name: Русский
      link: ru
      lang: ru