site_name: LDYOM Docs

theme:
  name: material
  language: en

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

nav:
  - English:
    - Overview : index.md
    - Basics : 
      - Install : en/Basics/install.md
      - Simple mission : en/Basics/simple_mission.md
  - Русский:
    - Обзор : ru/index.md
    - Основы : 
      - Установка : ru/Basics/install.md
      - Простая миссия : ru/Basics/simple_mission.md
  - LCAPI:
    - Opcodes: LCAPI/opcodes.md